### ISSUE TITLE
hexrayscodexplorer not work in ida 6.6 

### ISSUE THREAD

**Issue by ling245100108** [REhints/HexRaysCodeXplorer#11]
I download hexrayscodexplorer1.6 plw and p64 to ida plugin direcotory. It has this error:
LoadLibrary(C:\tool\IDAPro6.6\plugins\HexRaysCodeXplorer.p64) error: (can't find specified program)。
C:\tool\IDAPro6.6\plugins\HexRaysCodeXplorer.p64: can't load file

but if I use hexrayscodexplorer 1.5 , It can work.

**Comment by matrosov** [comment]
Thank you for your feedback. It's not a bug. The idea of CodeXplorer plugin is supporting a latest version of Hex-Rays IDA and Decompiler. Currently version 1.6 is not working with older version of SDK than 6.8. It's why the plugin is non loading correctly.

What you can try to do: compile source code with older version of SDK (it will be need some fixes into the code) or use older version [1.5](https://github.com/REhints/HexRaysCodeXplorer/releases/tag/1.5). It's should be works well with IDA v6.6. 

Happy RE with CodeXplorer ;)

**Comment by computerline1z** [comment]
ling245100108 : could use my fork to build for IDA v6.6, it also fix to work with IDA x64 
https://github.com/computerline1z/HexRaysCodeXplorer

Happy RE :)
