### ISSUE TITLE
IDA 6.6 support

### ISSUE THREAD

**Issue by Karaulov** [REhints/HexRaysCodeXplorer#13]
![wxyzknx](https://cloud.githubusercontent.com/assets/6445336/8397896/eee510f6-1de3-11e5-98ee-4005d000049c.png)

LoadLibrary(C:\IDAPro6.6full\IDAPro6.6\plugins\HexRaysCodeXplorer.plw) error: Not found specified procedure.
C:\IDAPro6.6full\IDAPro6.6\plugins\HexRaysCodeXplorer.plw: can't load file

**Comment by matrosov** [comment]
Unfortunately we not support old versions of IDA and Decompiler. In development process we always focused on latest versions of IDA/Decompiler and SDK. I can suggest just use older version of CodeXplorer (1.5 for 6.6) or update your Hex-Rays version.

**Comment by Karaulov** [comment]
This is last IDA. There's this eror!
