### ISSUE TITLE
bad names

### ISSUE THREAD

**Issue by Karaulov** [REhints/HexRaysCodeXplorer#14]
https://github.com/REhints/HexRaysCodeXplorer/issues/13

and

http://i.imgur.com/Ovi1zmG.png
- bad names (cropped text. so necessary?)
![ovi1zmg](https://cloud.githubusercontent.com/assets/6445336/8398293/d6a86062-1df0-11e5-9011-611940de3a7c.png)

**Comment by matrosov** [comment]
Looks as error. Could you provide more information about this issue? We need a sample or more context information when this kind of issues happens.

**Comment by Karaulov** [comment]
Maybe the problem is that I have not downloaded the plugin from your site?

https://github.com/computerline1z/HexRaysCodeXplorer/tree/master/bin/v1.7%20%5BNSEC15%20Edition%5D%20IDA%206.6

**Comment by Karaulov** [comment]
I used IDA 6.6 + hexrays + exrapass + classinformer, and then HexRaysCodeXplorer

**Comment by Karaulov** [comment]
It is an attempt to complete the decompilation: Game.dll of the game "Warcraft III".

http://rghost.ru/6TNjWmgB8 (http://rghost.net/6TNjWmgB8)

**Comment by matrosov** [comment]
I'm tested latest version of CodeXplorer on this files. It's works well. Looks like this bug is doesn't contains in original version. You would discuss this issue to the fork authors.

Thanks for your feedback!
