### ISSUE TITLE
IDA 6.6 - LATEST. Not working!

### ISSUE THREAD

**Issue by Karaulov** [REhints/HexRaysCodeXplorer#15]
![bh3197v](https://cloud.githubusercontent.com/assets/6445336/8407550/55ee740e-1e70-11e5-8681-350c9698d392.png)

I'm using the latest IDA 6.6! Writes function not found: get_name_2 and get_ea_name !!

How to download HexRaysCodeXplorer for latest 6.6 ida?

**Comment by XVilka** [comment]
@Karaulov latest IDA is 6.8 version, check the site https://www.hex-rays.com/products/ida/
