### ISSUE TITLE
How to reconstruct type from multiple locations?

### ISSUE THREAD

**Issue by temp331674** [REhints/HexRaysCodeXplorer#18]
I'm wondering if it's possible to reconstruct a type from multiple functions. For example, this function assigns the vtable but it does not use all fields.

Before reconstruct type:

![image](https://cloud.githubusercontent.com/assets/13005361/10113355/ca897f9e-63e3-11e5-9bad-e9b14aab6ba3.png)

After reconstruct type:

![image](https://cloud.githubusercontent.com/assets/13005361/10113360/db387c6e-63e3-11e5-987e-cedf214f7fd1.png)

That works perfectly. However, it only creates the fields that are specifically used here.

Many more fields of this type are only used in other functions. Reconstruct type seems to just load the existing struct instead of adding newly discovered fields, resulting in weird gap_F8[44] fields. (v2 is a NetConnection *)

![image](https://cloud.githubusercontent.com/assets/13005361/10113400/2ba58674-63e4-11e5-85f5-ea8096126b4a.png)

Does your plugin or IDA itself provide an easy way to solve this?

**Comment by Trass3r** [comment]
Yeah it should load the existing one and refine it.
The code is somewhere in there: https://github.com/REhints/HexRaysCodeXplorer/blob/master/src/HexRaysCodeXplorer/TypeReconstructor.cpp#L500

**Comment by mrgreywater** [comment]
+1
