### ISSUE TITLE
Crash with REconstruct Type

### ISSUE THREAD

**Issue by trixnz** [REhints/HexRaysCodeXplorer#19]
With the latest IDA 6.9, when I attempt to to reconstruct a variable, IDA crashes.

I traced this back to [TypeReconstructor.cpp:627](https://github.com/REhints/HexRaysCodeXplorer/blob/master/src/HexRaysCodeXplorer/TypeReconstructor.cpp#L627). For one reason or another, `lvar_t * lvar =  vu.item.get_lvar();` returns nullptr, which is passed into `make_pointer` and subsequently crashes IDA.

I am testing this on IDA64 with version 6.9.

**Comment by matrosov** [comment]
Problem confirmed. Working on fix.

**Comment by matrosov** [comment]
fixed in commit  [5e7ce2534a9553a5e0b5f0d054d79f6317b1008a](https://github.com/REhints/HexRaysCodeXplorer/commit/5e7ce2534a9553a5e0b5f0d054d79f6317b1008a)
