### ISSUE TITLE
CodeXplorer doesn't seem to load on IdaPro

### ISSUE THREAD

**Issue by OpM3TA** [REhints/HexRaysCodeXplorer#22]
-- snip --

Edit:
My apologies, I did find the old versions of HRCX on GitHub, whihc version works with IDAPro 6.8?
https://github.com/REhints/HexRaysCodeXplorer/tree/master/bin

**Comment by matrosov** [comment]
Since latest two commits main branch focused to stable support for v6.9. But compiled binaries for v6.8 still located [here](https://github.com/REhints/HexRaysCodeXplorer/tree/master/bin/v2.0%20%5BBlackHat%20Edition%5D/IDA%20v6.8/Win).
