### ISSUE TITLE
Linux branch not working in IDA 6.9

### ISSUE THREAD

**Issue by agentzappo** [REhints/HexRaysCodeXplorer#27]
Commit from Dec 2015 says .plw was updated for IDA 6.9 in Linux, but plugin does not appear after copying to $IDA/plugins

**Comment by JivanH** [comment]
Maybe you should  use .plx file in Linux.

**Comment by matrosov** [comment]
It works fine in my case. If you still have this issue please let me know more context and make a double check for use right binaries for Linux.
