### ISSUE TITLE
Support option for type creation fields to be in hex

### ISSUE THREAD

**Issue by grant-h** [REhints/HexRaysCodeXplorer#30]
Just a small nit when reconstructing types. It's hard to compare memory traces to undefined field_%d variables as measurements are usually done in hex. I may submit a PR for this...

Personally I think there shouldn't be an option and that the default should be hex.

https://github.com/REhints/HexRaysCodeXplorer/blob/master/src/HexRaysCodeXplorer/TypeReconstructor.cpp#L547-L548

**Comment by Atvaark** [comment]
Agreed.

Adding new fields to a reconstructed type in the structs window also uses the field offset in hex.

**Comment by matrosov** [comment]
Good idea. We will include this fix in the next release.
