### ISSUE TITLE
Not working with IDA 6.95

### ISSUE THREAD

**Issue by krispychipz** [REhints/HexRaysCodeXplorer#32]
Hello,

I have downloaded the src and recompiled with Visual Studio 2015 for IDA 6.95 but when I load the plugin into the plugins/ folder, it does not seem to load CodeXplorer. Does not show up in the plugins submenu. 
I have tried running your precompiled v2.0 and v1.7 binaries for IDA 6.8 and 6.9 as well with the same results. 
Windows 10 x64
IDA 6.95
IDASDK 6.95
x86 Decompiler 2.4.0.160808

When compiling I also got errors for missing CallGraphBuilder.cpp and JsonParser.cpp. Where are these files located? They are not in the SDK or in your source distribution. To allow compilation, I have removed these two files from the vcxproj file. 

Thanks.

**Comment by mrJingl3s** [comment]
Any progress on this bug for IDA Pro 6.95? Will you release a build for 6.95?

**Comment by matrosov** [comment]
I add compiled binaries for IDASDK v6.95. Check the latest commit 04e3dcf9c337d325da5b9f66df7597612fdf37b8
