### ISSUE TITLE
Access violation in process_rtti

### ISSUE THREAD

**Issue by kiwidoggie** [REhints/HexRaysCodeXplorer#35]
I get an access violation for what I believe is cross-thread issue maybe.  It says that it had an violation accessing memory or writing to memory that it shouldn't have. I narrowed down the error with building my own version (IDA 6.8 SDK) to the process_rtti() function in ObjectExplorer.cpp.

I made a quick and dirty patch to fix my issue for now, but I'm not familiar with the framework and would prefer someone that knows what they are doing to look into it. The crash happens within the cat_sprint function in qstring.

Line 291

```
    std::stringstream s_Stream;

    s_Stream << "0x" << rtd << std::hex << ":  " << name;

    /* qstring tmp;

    tmp.cat_sprnt(" 0x%x:  %s", rtd, name);*/

    rtti_list.push_back(s_Stream.str().c_str());
```

**Comment by matrosov** [comment]
fixed
