### ISSUE TITLE
Failed on load on ida 6.95 / osx

### ISSUE THREAD

**Issue by brinlyau** [REhints/HexRaysCodeXplorer#37]
Wont load on IDA 6.95 on OSX (10.12). Did I miss something obvious? :)

Log:
dlopen(/Applications/IDA Pro 6.95/idaq64.app/Contents/MacOS/plugins/HexRaysCodeXplorer.pmc64): dlopen(/Applications/IDA Pro 6.95/idaq64.app/Contents/MacOS/plugins/HexRaysCodeXplorer.pmc64, 2): Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5c_strEv
  Referenced from: /Applications/IDA Pro 6.95/idaq64.app/Contents/MacOS/plugins/HexRaysCodeXplorer.pmc64
  Expected in: /usr/lib/libstdc++.6.dylib
 in /Applications/IDA Pro 6.95/idaq64.app/Contents/MacOS/plugins/HexRaysCodeXplorer.pmc64

**Comment by brinlyaus** [comment]
Ooops, I accidentally closed this. :)

**Comment by ckcfcc** [comment]
bump

**Comment by vcarus** [comment]
Same issus here.
Any ideas?

**Comment by nyx0** [comment]
What binary did you use?

**Comment by sonic414** [comment]
Using bin/Hex-Rays Plugin contest/2015/Mac  binaries gives me the same errors.
No uptodate binaries exist for Mac.

**Comment by nyx0** [comment]
if you are still on IDA Pro 6.95 you can compile it to have an uptodate binary

**Comment by matrosov** [comment]
We don't support 6.95 anymore.
