### ISSUE TITLE
two files not found when building from source

### ISSUE THREAD

**Issue by TakahiroHaruyama** [REhints/HexRaysCodeXplorer#41]
Hi, I had the following build errors. I found the same question before but can I simply delete the lines from .vcxproj file? 

1>  CallGraphBuilder.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'CallGraphBuilder.cpp': No such file or directory
...
1>  JsonParser.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'JsonParser.cpp': No such file or directory

**Comment by matrosov** [comment]
Sorry about that. It's some features from upcoming version. Just delete the files from project config and it will be solve the problem.

**Comment by TakahiroHaruyama** [comment]
OK thanks!!
