### ISSUE TITLE
IDA 7 support ?

### ISSUE THREAD

**Issue by trou** [REhints/HexRaysCodeXplorer#44]
Hello,
have you already working on IDA 7 support? 
If not, I might try to have a look.

Raphaël

**Comment by matrosov** [comment]
Hey Raphael,

I am currently looking on it. It needs a lot of work because they changed a lot of functions and even a logic for them too. I am currently thinking about for refactoring all the project because of that. But if you want to look feel free with pull requests.   

Thanks for your support!

**Comment by philophys** [comment]
Hey @matrosov, is there any improvement on this 🤔

**Comment by sunnyelf** [comment]
Not support for IDA 7.0

**Comment by kiwidoggie** [comment]
@matrosov Do you have this work in a feature branch yet?

**Comment by matrosov** [comment]
We are working on an update. It's a lot of changes in new SDK which is needed to change over 50% of the current code base. Also IDA starts to support some of the concepts for C++ vtables reconstruction. We try to figure out the best way to not duplicate this functionality in CodeXplorer. But you can use CodeXplorer with x86 version is still compatible with old-style plugins.

**Comment by zwzy** [comment]
@matrosov any ETA?

**Comment by matrosov** [comment]
Experimental support for IDA 7 added in the current version (thx @a1ext ). We are working on some improvements.

**Comment by michaelpittino** [comment]
Would you mind providing binaries for it? Thanks!

**Comment by paulsapps** [comment]
Should the latest binaries work with IDA 7? I download an added to plugins dir but it never appears?

**Comment by michaelpittino** [comment]
It does for me.

**Comment by paulsapps** [comment]
I managed to get it working, had it one level too far down, user error :1st_place_medal:
