### ISSUE TITLE
I have no idea

### ISSUE THREAD

**Issue by alialwahish** [REhints/HexRaysCodeXplorer#46]
Hi I just wanna know what am missing you are explaining everything except how to install or idk where to start if this is for professional it won't hurt to add how to get started don't be so proud with what you know cause there's always someone know more and at some point you started at some point 

Thanks 
Ali Bayati

**Comment by SilverBut** [comment]
Really wondering if **shift, comma, period and question marks** are missing from your keyboard.
Maybe no one will response it if you can not describe your problem in English.

**Comment by alialwahish** [comment]
Yea yea i knew it , don’t bother yourself with my comment am using snowman and it’s for regular people like me not intelligent like you 

Thanks 
Ali
