### ISSUE TITLE
Doesn't compile - Missing definition of custom_viewer_handlers_t

### ISSUE THREAD

**Issue by wangray** [REhints/HexRaysCodeXplorer#47]
I get several errors: 
At ObjectExplorer.cpp:634,
```
custom_viewer_handlers_t cvh = custom_viewer_handlers_t();
cvh.keyboard = ct_object_explorer_keyboard;
```
`custom_viewer_handlers_t` is simply not defined anywhere. 

Also, at three locations
`set_custom_viewer_handlers(si->cv, NULL, si);` throws an error `function does not take 3 arguments`.

My build system is Visual Studio with IDA SDK 6.8, but this seems to a problem with the codebase.

**Comment by SilverBut** [comment]
SDK of 6.8 is different with currently used version

You can see [this gist](https://gist.github.com/agelastic/0bf61260e21c2bccf531) to modify the code. 

Also it would be better if we can try to use some precompile commands solve problems like this completely? @matrosov

**Comment by matrosov** [comment]
We always focusing on support only recent version of IDA and Decompiler. The main reasons are to always use new features to improve CodeXplorer.
