### ISSUE TITLE
Request a release version for Windows, IDA Pro 7.0

### ISSUE THREAD

**Issue by skyel1u** [REhints/HexRaysCodeXplorer#54]
[build.zip](https://github.com/REhints/HexRaysCodeXplorer/files/1716741/build.zip)
Dear developers:
I have build the plugin from the latest code, but it seems didn't work on windows 10 17093, IDA Pro 7.0, I can't find the load info of this plugin when IDA start. I would appreciate if anyone could help, thanks~

![1](https://i.loli.net/2018/02/12/5a81ab3ebe1f7.jpg)

Here is my build plugin:
https://mega.nz/#!akxDmDYJ!BjtFQNCeCGCQlx6NaQX-G6ThWVpTrjKNEO1cq4RJq5E

**Comment by stek29** [comment]
It is not supposed to be listed in that window
Start it, open pseudocode view and right click. You should see new options added by this plugin.
I tried your dlls and they work fine for me with IDA7.0 / hexrays7

**Comment by stek29** [comment]
Here's build for Win/IDA7.0/hexrays7 by a friend of mine.

[HexRaysCodeXplorerWin_IDA7.0_hexrays7_7a2716e.zip](https://github.com/REhints/HexRaysCodeXplorer/files/1808762/HexRaysCodeXplorerWin_IDA7.0_hexrays7_7a2716e.zip)

**Comment by skyel1u** [comment]
Thanks, it loaded.

**Comment by congpx** [comment]
Thanks. It works

> Here's build for Win/IDA7.0/hexrays7 on [7a2716e](https://github.com/REhints/HexRaysCodeXplorer/commit/7a2716eb9cb8bb62306a3edcb569dfa219a99c1f) by a friend of mine.
> 
> [HexRaysCodeXplorerWin_IDA7.0_hexrays7_7a2716e.zip](https://github.com/REhints/HexRaysCodeXplorer/files/1808762/HexRaysCodeXplorerWin_IDA7.0_hexrays7_7a2716e.zip)
