### ISSUE TITLE
How to find path?

### ISSUE THREAD

**Issue by andrewfree** [REhints/HexRaysCodeXplorer#55]
I have the IDA Pro (64-bit) program installed and wanted to installed this as an extension is that possible? How would I find the <PATH_TO_IDA> info for my makefile stuff?

**Comment by stek29** [comment]
IDA_DIR is path where ida is installed ($IDA_DIR/ida.dll, $IDA_DIR/ida64.dll & $IDA_DIR/plugins/hexrays_sdk should exist)
IDA_SDK is path where ida sdk is located. ida sdk is available at ida download center.
code also seems to refer to $IDA_DIR/plugins/SDK, so you might want to place IDA_SDK in that folder.
