### ISSUE TITLE
DLL not loading?

### ISSUE THREAD

**Issue by vanhauser-thc** [REhints/HexRaysCodeXplorer#58]
I am running IDA 7.1 x64 on Windows.

I compiled HexRaysCodeXplorer and the resulting DLL is present in the /plugins/ directory.

However it seems the DLL is not loaded.
No new entry is present in Edit->Plugins, nor does the decompile tab get new items when right clicking.
Also no message concerning HexRaysCodeXplorer is visible in the Messages window.

**Comment by stek29** [comment]
Works fine for me with IDA7.0

**Comment by matrosov** [comment]
After #57 everything works well on IDAv7.1 (thx @stek29)

**Comment by vanhauser-thc** [comment]
yes that patch fixes it. thanks.
