### ISSUE TITLE
32-bit binary support?

### ISSUE THREAD

**Issue by Fewmitz** [REhints/HexRaysCodeXplorer#61]
The context menu in the decompiler output menu only shows up when reverse engineering 64-bit binaries. Is this a lack of support inside the plugin or should I do some other troubleshooting?

Additionally, when I setup to build it (thinking maybe I just needed a different build of the plugin) I get the following linker error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'C:\Program Files\IDA 7.1\plugins\HexRaysCodeXplorer64.dll'	HexRaysCodeXplorer	D:\misc\HexRaysCodeXplorer-master\HexRaysCodeXplorer-master\src\HexRaysCodeXplorer\LINK	1	

```

Where I have the following set in the prop sheet:

```
    <IDADIR>C:\Program Files\IDA 7.1</IDADIR>
    <IDASDK>D:\idasdk71\idasdk71</IDASDK>
```

Help with either of these issues is appreciated.

**Comment by matrosov** [comment]
I can't reproduced the same problem on my machine. Could you provide more details of this behavioral?

**Comment by filiphhh** [comment]
In the release section you've only uploaded a plugin compiled for x64 which doesn't get loaded in Ida Pro (32-bit), Ida Pro (64-bit) won't decompile 32 bit binaries and will instead prompt you to use the 32-bit version.

**Comment by ecx86** [comment]
Yeah, it would be nice to have a compiled binary for IDA 32-bit not just IDA 64.

**Comment by matrosov** [comment]
I will be releasing a minor release of the plugin over the weekend. It will be both versions (32 and 64 bit) of plugin included.

**Comment by AeonLucid** [comment]
@matrosov Any update?

**Comment by matrosov** [comment]
@AeonLucid HexRaysCodeXplorer32.dll added to the previous release. New release needs a bit more time trying to make new features working stable.
