### ISSUE TITLE
plugin does not work for ida-7.1 (linux)

### ISSUE THREAD

**Issue by kemingzhang** [REhints/HexRaysCodeXplorer#67]
I compiled the linux shared libs with both EA=0 and EA=1, copied HexRaysCodeXplorer64.so  HexRaysCodeXplorer.so to the ida-7.1/plugins/ and then restarted IDA. The HexRaysCodeXplorer plugin did  not show up. I also tried to add the the plugin entry in  ida-7.1/plugins/plugins.cfg and it did not work either. Please advise. Thanks.

**Comment by matrosov** [comment]
CodeXplorer needs an active license for Hex-Rays Decompiler because a significant part of the plugin uses decompiler API.  Do you have a licence for decompiler? Also, we have compiled and tested linux binaries for the recent version.

**Comment by kemingzhang** [comment]
My Hex-Rays Decompiler's license is active. I also tried to use the binaries released from HexRaysCodeXplorer-2.1-linux64.tar.gz  and the plugin did not show up either. Is there anyway we can troubleshoot this? My OS Ubuntu 16.04.5 LTS (Xenial Xerus). Thanks.

**Comment by kemingzhang** [comment]
Ah, the plugin did not show up in IDA|Edit|Plugins, but it does show up in the right-click pop menus. So it is a bit confusing for new users like me, but it works. Thank you.
