### ISSUE TITLE
IDA 7 support

### ISSUE THREAD

**Issue by eagleFromHeaven** [REhints/HexRaysCodeXplorer#71]
Hey can you please:
1. add Ida 7 support
2. add automatically analyze of struct? like solve this Ida line: `*(&v15 + some_var - 77) = *(&v15 + some_var - 76) - *(&v15 + some_var - 77);`  to a normal strucr?

**Comment by matrosov** [comment]
Thanks for the feedback. The backward compatibility is not a priority for this project. We always try to support the newest features of recent IDA and Hex-Rays versions to improve the plugin. Unfortunately, support of older versions needs a time investment for extra development which we decide to use to develop new features.    

Good point about structures I will take look at what I can do there.
