### ISSUE TITLE
Unable to load on IDA linux (latest version) and unable to compile in lu

### ISSUE THREAD

**Issue by nahualito** [REhints/HexRaysCodeXplorer#72]
I'm trying to load the plugin against the latest version of the linux IDA, the compiled version refuses to load completely, and the source fails to load with:

oiajsd@ouipreqwouiperwquiopreqw:~/tools/HexRaysCodeXplorer/src/HexRaysCodeXplorer$ IDA_DIR=/home/oiajsd/ida-7.2/ IDA_SDK=/home/oiajsd/idasdk72 EA64=0 make -f makefile.lnx 
+ IDA_DIR=/home/oiajsd/ida-7.2/
+ IDA_SDK=/home/oiajsd/idasdk72
+ EA64=0
+ make -f makefile.lnx
rm -f ./CodeXplorer.o ./CtreeGraphBuilder.o ./ObjectExplorer.o ./TypeReconstructor.o ./CtreeExtractor.o ./TypeExtractor.o ./Utility.o ./MSVCObjectFormatParser.o ./IObjectFormatParser.o ./GCCObjectFormatParser.o ./GCCVtableInfo.o ./GCCTypeInfo.o ./Debug.o HexRaysCodeXplorer.so
g++ -m64 -fPIC -D__LINUX__ -D__PLUGIN__ -std=c++11 -D__X64__ -D_GLIBCXX_USE_CXX11_ABI=0 -I/home/oiajsd/idasdk72/include -I/home/oiajsd/ida-7.2//plugins/hexrays_sdk/include -c CodeXplorer.cpp -o CodeXplorer.o
CodeXplorer.cpp: In function ‘bool display_ctree_graph(void*)’:
CodeXplorer.cpp:348:36: error: ‘WOPN_MENU’ was not declared in this scope
  display_widget(widget, WOPN_TAB | WOPN_MENU);
                                    ^~~~~~~~~
CodeXplorer.cpp:348:36: note: suggested alternative: ‘WOPN_TAB’
  display_widget(widget, WOPN_TAB | WOPN_MENU);
                                    ^~~~~~~~~
                                    WOPN_TAB
makefile.lnx:50: recipe for target 'CodeXplorer.o' failed
make: *** [CodeXplorer.o] Error 1
oiajsd@ouipreqwouiperwquiopreqw:~/tools/HexRaysCodeXplorer/src/HexRaysCodeXplorer$ 

Is anyway I can compile this for the latest version? Am I missing something? I did make sure the SDK was compiled 

Thank you

**Comment by matrosov** [comment]
Are you have both Hex-Rays Decompiler and IDA SDK's right? What is your Linux version?
