### ISSUE TITLE
Solution to compiling error in VS 2017 for IDA 7.2 (Windows)

### ISSUE THREAD

**Issue by peta909** [REhints/HexRaysCodeXplorer#74]
HI,
I cloned the codes and tried to compile it in VS2017 with IDA 7.2. It threw many errors related to "WOPN_ONTOP" and "WOPN_MENU" being undeclared identifiers.

I added the following lines to "Common.h"
#define WOPN_ONTOP              0x08 
#define WOPN_MENU              0x10

I hope this can help someone else that faced similar errors.

**Comment by matrosov** [comment]
That's weird. I can't reproduce the same problem on my end.

**Comment by computerline1z** [comment]
in 7.2 version, their replace WOPN_ONTOP and WOPN_MENU with WOPN_TAB, you could modify code to fix that.

**Comment by matrosov** [comment]
Do you have these errors with this branch (https://github.com/REhints/HexRaysCodeXplorer/tree/reconstructable_type)? It's a most recent version of the project and was originally developed/tested on VS2017.

**Comment by xeropresence** [comment]
Hey, I was able to compile the reconstructable_type branch just fine, but the plugin would not load and no debug output was generated in ida's log. Compiling the master branch with the 7.2 sdk and the addition to common.h resulted in a working plugin for 7.2

**Comment by blackzert** [comment]
To use the branch reconstructable_type branch you have to create config with name "codeexplorer.cfg" in %IDADIR%/cfg with defining following hotkeys as you prefer:
HOTKEY_DISPLAY_GRAPH
HOTKEY_OBJECT_EXPLORER
HOTKEY_RECONSTRUCT_TYPE
HOTKEY_JUMP_TO_DISASM
HOTKEY_EXTRACT_TYPES
HOTKEY_EXTRACT_CTREE
HOTKEY_CTREE_VIEW
HOTKEY_SHOW_COPY_ITEM_OFFSET
HOTKEY_RENAME_VARS

You can follow the code https://github.com/REhints/HexRaysCodeXplorer/blob/335ca5856544c81f687cd9bf2e2527a028cad59a/src/HexRaysCodeXplorer/CodeXplorer.cpp#L751 to understand its values.

**Comment by computerline1z** [comment]
you could create a file with name codeexplorer.cfg in <IDADIR>/cfg directory with the following content

```
HOTKEY_DISPLAY_GRAPH="T"
HOTKEY_OBJECT_EXPLORER="O"
HOTKEY_RECONSTRUCT_TYPE="R"
HOTKEY_JUMP_TO_DISASM="E"
HOTKEY_EXTRACT_TYPES="S"
HOTKEY_CTREE_VIEW="V"
HOTKEY_SHOW_COPY_ITEM_OFFSET="Q"
HOTKEY_RENAME_VARS="C"
```

**Comment by matrosov** [comment]
Okay, I think that's a solution. The issue should be resolved now.
