### ISSUE TITLE
can`t  see ctree graph view in ida pro 7.0

### ISSUE THREAD

**Issue by kuh3h3** [REhints/HexRaysCodeXplorer#75]
build ok with ida 7.0 sdk on vs 2017.
but i can` see the contents when click display ctree graph.
back ground color and font color is too similar.
is there any color adjust setting?

http://prntscr.com/myk89w

**Comment by matrosov** [comment]
I think the problem is tide to SDK version. You need to build with recent one v7.2 and it works like charm.
