### ISSUE TITLE
Error: The specified procedure could not be found

### ISSUE THREAD

**Issue by hatRiot** [REhints/HexRaysCodeXplorer#77]
Building latest master with Visual Studio 2017 (SDK 10.0.17134.0) with IDA Pro and Hex-Rays x64 7.2. Builds fine (after adding defines as per issue #74 ) with IDA SDK 7.3, but doesn't load:

```
LoadLibrary(C:\Program Files\IDA 7.2\plugins\HexRaysCodeXplorer.dll) error: The specified procedure could not be found.
C:\Program Files\IDA 7.2\plugins\HexRaysCodeXplorer.dll: can't load file
```

Any ideas?

**Comment by computerline1z** [comment]
You can copy HexRaysCodeXplorer.dll to IDADIR and use dependency warlker to check if all dll load fine.
