### ISSUE TITLE
ReconstructableType.h and ReconstructableType.cpp are missing from master

### ISSUE THREAD

**Issue by rossi9** [REhints/HexRaysCodeXplorer#78]
The files are missing from the master branch but are referenced in multiple files
including the .vcxproj file.
CodeXplorer.cpp
GCCObjectFormatParser.cpp
GCCTypeInfo.cpp
GCCVtableInfo.cpp
HexRaysCodeXplorer.vcxproj

That is, of course, assuming the project is supposed to build off the master branch.
Just clone the master to some directory other than your regular development directory
and try to build.

Thanks.

**Comment by matrosov** [comment]
I will fix it today, you right for dev purposes better to create a development branch. The VS project file outdated as well as makefile's, only source code changes pushed so far. Thank you for reporting this issue.

**Comment by trou** [comment]
Hi Alex,
it seems MicrocodeExtractor.h and MicrocodeExtractor.cpp are missing too

**Comment by dav-rgb** [comment]
hi all, yes I have the same problem for linux installation.
Missing files are : 
- MicrocodeExtractor.h and MicrocodeExtractor.cpp
- ReconstructableType.h and ReconstructableType.cpp
- reconstructed_place_t.h and reconstructed_place_t.cpp
Thanks @matrosov

**Comment by matrosov** [comment]
Thanks I will update makefile’s as well, currently was able to test only on win and forgot to update linux/osx build environment.

**Comment by matrosov** [comment]
fixed
