### ISSUE TITLE
Object Explorer Window Opens Unexpectedly (without hotkey)

### ISSUE THREAD

**Issue by rhettc** [REhints/HexRaysCodeXplorer#8]
Several keyboard buttons including the arrow keys will cause the Object Explorer window to open. I think the issue is here: 
https://github.com/REhints/HexRaysCodeXplorer/blob/master/src/HexRaysCodeXplorer/CodeXplorer.cpp#L425

Because all of the keycodes are not defined in the above location (only two,) I'm guessing that whenever a keyboard button is pressed where lookup_key_code returns zero, this condition evaluates true and opens the window:

https://github.com/REhints/HexRaysCodeXplorer/blob/master/src/HexRaysCodeXplorer/CodeXplorer.cpp#L395

**Comment by matrosov** [comment]
Thanks for pointing us to this issue. Should be fixed in v1.6 which will released at [NSec](https://www.nsec.io/) talk.

**Comment by matrosov** [comment]
fixed in version [v1.6](https://github.com/REhints/HexRaysCodeXplorer/releases/tag/1.6)
