### ISSUE TITLE
Shortcuts conflicts

### ISSUE THREAD

**Issue by trou** [REhints/HexRaysCodeXplorer#80]
Hi,
the new HexRaysCodeXplorer's microcode view shortcut conflicts with a builtin from Hex-Rays:
```
Conflicting shortcut: M; Candidate actions:
	codexplorer::microcode_view (Microcode View)
	hx:Enum (Enu&m)
```
Maybe Ctrl-Shift-M would be better ?

**Comment by trou** [comment]
T also conflicts with "structure offset"

**Comment by matrosov** [comment]
Thank you for fixing this bug over pull request #79
