### ISSUE TITLE
Commit 64-bit binaries to repo

### ISSUE THREAD

**Issue by dwendt** [REhints/HexRaysCodeXplorer#9]
Reading the slide-deck, this is capable of compiling as a 64-bit plugin -- could those bins be committed to the repo so that people don't need to build it for themselves?

**Comment by matrosov** [comment]
The next release with full support x64 version of decompiler scheduled after preso "Object Oriented Code RE with HexraysCodeXplorer" at [NSec](https://www.nsec.io/) conference.

**Comment by matrosov** [comment]
fixed in [v1.6](https://github.com/REhints/HexRaysCodeXplorer/releases/tag/1.6)
